services:
  app:
    build: .
    ports:
      - "8000:80"
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/share/nginx
    networks:
      - sebrae-network

  mysql-app:
    image: mysql:5.7
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0?Tpax13
      MYSQL_DATABASE: sebrae
      MYSQL_USER: garre
      MYSQL_PASSWORD: 0?Tpax13
    ports:
      - "3306:3306"
    networks:
      - sebrae-network

networks:
  sebrae-network:
    driver: bridge